# Toolbox - Joint-Positiont
# -------------------------------
# Description:
#   Message-type for Joint-Position with External Axis.
#   A more user friendly representation of joint-position 
#   with external axis
#
# Version:
#   0.1 -   Initial version
#           [20.01.2024] - Jan T. Olsen
# -------------------------------

# Joints
float64 qE
float64 q1
float64 q2
float64 q3
float64 q4
float64 q5
float64 q6
